use_nerdfont = true

[theme]
background = "#282828"
primary = "#fbf1c7"
secondary = "#584945"
title = "#d65d0e"
playing = "#98971a"
playing_selected = "#689d6a"
playing_bg = "#282828"
highlight = "#fbf1c7"
highlight_bg = "#928374"
error = "#fbf1c7"
error_bg = "#cc241d"
statusbar = "#1d2021"
statusbar_progress = "#b8bb26"
statusbar_bg = "#98971a"
cmdline = "#fbf1c7"
cmdline_bg = "#1d2021"
search_match = "#fb4934"
